### ISSUE TITLE
Browser error when using with Angular 8

### ISSUE THREAD

**Issue by nelson777** [Richienb/url-exist#29] opened 2020-11-10 23:28 UTC
I'm getting the following error when I try to use this package with Angular 8:

```
Uncaught TypeError: __webpack_require__(...).create is not a function
    at Object../node_modules/url-exist/index.js (vendor.js:223602)
    at __webpack_require__ (runtime.js:80)
    at Module../src/app/videos/live/live.component.ts (main.js:6441)
    at __webpack_require__ (runtime.js:80)
    at Module../src/app/app.module.ts (main.js:1342)
    at __webpack_require__ (runtime.js:80)
    at Module../src/main.ts (main.js:7008)
    at __webpack_require__ (runtime.js:80)
    at Object.0 (main.js:7031)
    at __webpack_require__ (runtime.js:80)

```
**To Reproduce**
npm i url-exist  **or** yarn add url-exist

in Angular 8 component:

	import urlExist from 'url-exist'; 
        (...)

	checkUrl(url) {
		let result;
		try {
			let r = await urlExist(TEST_URL);
			result = r ? 'OK' : 'FAIL';
		} catch(err) {
			result = 'FAIL';
		}
		return result;
	}

**Expected behavior**
Return 'FAIL' or 'OK'

**Desktop (please complete the following information):**

-   OS: Host: Linux Mint 20 VM: Ubuntu /Vagrant VM: Ubuntu 18.04
-   Browser Chromium
-   Version 2.02

**Additional context**

As this is an angular project webpack isn't used directly in the project.

**Comment by Richienb** [comment] 2020-11-11 03:49
@nelson777 Can you reproduce this issue in a seperate repo?

**Comment by nelson777** [comment] 2020-11-12 03:05
Sure... here it is:

https://github.com/nelson777/url-exists-error-example

I use Linux so, the below instructions are for Linux box with vagrant installed. But you should have to do only minor changes to run in other OSs.

Please use the following steps to reproduce the error:

1. mkdir error-example && cd error-example
2. git clone https://github.com/nelson777/url-exists-error-example .
If your local network doesn't use the 192.168.0.* mask please edit Vagrantfile and change accordingly
3. vagrant up 
4. vagrant ssh
5. cd /vagrant/a8example
6. yarn start

open http://192.168.0.133:4200 (or the ip you configured in Vagrantfile) and check the console to see the error.

To see that the project runs fine without url-exist please comment url-exist's related lines in src/app/app.component.ts files (lines 2 and 11).

**Comment by Richienb** [comment] 2020-11-12 06:58
ky-universal has been created to cater to both browsers and Node.js. In Node.js, it uses the commonjs module system but the browser version uses ESM. When Angular tries to compile url-exist it recognizes that ky-universal is imported via commonjs but since it's in the browser, uses the [ESM bundle](https://github.com/sindresorhus/ky-universal/blob/5bf02df957654915ac2fc95d4f471c28759aa782/browser.js). Webpack then automatically tries to polyfill esm modules instead of automatically converting it to a commonjs module and hence `.create` doesn't exist on the imported object. Instead, only `.default` exists.

**Comment by nelson777** [comment] 2020-11-12 14:04
So... I understood your explanation, but the solution isn't evident to me. Can you see a solution to this or you're saying that url-exist isn't compatible with Angular 8?

**Comment by nelson777** [comment] 2020-11-12 19:30
I found that this works:

1.Install is-url-superb and ky-universal in the project. 
2.include these configs in tsconfig.json:

	"allowSyntheticDefaultImports": true,
	"esModuleInterop": true,

3.Create this file:

```
//file: test-url.ts
import isUrl from 'is-url-superb';
import kyUniversal from 'ky-universal';

export async function exists(url : string) : Promise<boolean> {
	const ky = kyUniversal.create({
		throwHttpErrors: false
	})
	
	if (!isUrl(url)) {
		return false
	}

	const response = await ky.head(url)
	return response !== undefined && !/4\d\d/.test('' + response.status)
}

```
5.import it like this:

    import { exists } from './test-url'

6.use it like this:

	exists("http://google.com").then(res => {
		console.log(res ? "Yes" : "No");		
	})

**Comment by Richienb** [comment] 2020-12-02 08:17
@nelson777 Try:

```js
import urlExist = require('url-exist');
```

**Comment by Richienb** [comment] 2021-01-27 14:02
Fixed in https://github.com/Richienb/url-exist/commit/16d6a8847d5df2379b8dc8e26ad57fafcffc2253

**Closed as completed by Richienb** 2021-01-27 14:02 UTC
